CREATE TABLE IF NOT EXISTS "crm_business" (
    "id" bigint NOT NULL,
    "name" varchar(255),
    "customer_id" bigint,
    "follow_up_status" bit,
    "contact_last_time" timestamp,
    "contact_next_time" timestamp,
    "owner_user_id" bigint,
    "status_type_id" bigint,
    "status_id" bigint,
    "end_status" int,
    "lose_reason_code" varchar(64),
    "end_remark" varchar(500),
    "version" int NOT NULL DEFAULT 0,
    "deal_time" timestamp,
    "total_product_price" decimal(24, 2),
    "discount_percent" decimal(5, 2),
    "total_price" decimal(24, 2),
    "remark" varchar(500),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
);
